# permissions for end users to edit imoocpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imoocpod-editor-role
rules:
- apiGroups:
  - xxx.bluemoon.com.cn
  resources:
  - imoocpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xxx.bluemoon.com.cn
  resources:
  - imoocpods/status
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - events
    - namespaces
    - nodes
    - pods
  verbs:
    - get
    - list
    - watch