# permissions for end users to view imoocpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imoocpod-viewer-role
rules:
- apiGroups:
  - xxx.bluemoon.com.cn
  resources:
  - imoocpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xxx.bluemoon.com.cn
  resources:
  - imoocpods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
