
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - xxx.bluemoon.com.cn
  resources:
  - imoocpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xxx.bluemoon.com.cn
  resources:
  - imoocpods/status
  verbs:
  - get
  - patch
  - update
